### PR TITLE
Update IronMonkePlugin.cs

### PR DESCRIPTION
**Pull request by Livku**

### CODE REVIEW

**Comment by Livku** [comment]
You Didn't Have To Delete Your Quest Mods,
What If Quest Mods Come Back?
Also, I Think 1.1.1 Or Something Is Now Multiplayer

**Comment by Livku** [comment]
So, Em, I Was Messing Around With The Code And Managed To Break Gorilla Tag Steam

**Comment by BzzzThe18th** [comment]
Well it's to separate mod users from normal users so normal users can play in any code without the risk of mod users ruining the vanilla experience for them. You can also just give your friend the code I'm pretty sure lmao. I also deleted my quest mods out of choice and for the good of the gorilla tag modding community.

**Comment by Livku** [comment]
OK.

I just want to know if I can play with friends using utilla.
And I was just asking about qmods, but I respect your decision.

**Comment by Livku** [comment]
Also, your mod has been stolen and put on other servers.
https://cdn.discordapp.com/attachments/912446119466909776/942409781954625536/IronMonke.dll
https://discord.com/channels/904926839724724284/912446119466909776/942409782151766036

I had the sever because 1.1.1 was multiplayer for a certain amount of time and this sever had 1.1.1 quest mods

**Comment by BzzzThe18th** [comment]
> Also, your mod has been stolen and put on other servers. https://cdn.discordapp.com/attachments/912446119466909776/942409781954625536/IronMonke.dll https://discord.com/channels/904926839724724284/912446119466909776/942409782151766036
> 
> I had the sever because 1.1.1 was multiplayer for a certain amount of time and this server had 1.1.1 quest mods

It would be appreciated if you could send a direct link to the server through discord direct messages. A message link in a server I am not a part of will not allow me to survey the message or server.

**Comment by Livku** [comment]
I'm sorry, but I left that discord before I saw your message.
But I found one of the guys who doesn't have your new mod but your old one.
he might have other stolen mods too.
https://github.com/MyNameIsCanadian/IronMonke

**Comment by Livku** [comment]
so, I like to look at all the gorilla tag modding discords out there and I found another with this mod

**Comment by Livku** [comment]
and another

**Comment by Livku** [comment]
> Well it's to separate mod users from normal users so normal users can play in any code without the risk of mod users ruining the vanilla experience for them. You can also just give your friend the code I'm pretty sure lmao. I also deleted my quest mods out of choice and for the good of the gorilla tag modding community.

so basically, I removed what happens when you leave the room, so if I don't have your mod enabled, I cant play mines, the lower part of canyons, and the low part of forest. I also can't go on the steps and certain parts of city.
Can you please tell where the cache is located so I can remove it.

**Pull request closed without merging**
